### ISSUE TITLE
result no audio

### ISSUE THREAD

**Issue by walhackmaster** [exwm/yt_clipper#17]
**Describe the Bug**
I followed the instruction after trim and get JSON file, then I drag it to yt_clipper_auto and success, Successfully generated, but when I play the video there no audio 

**How to Reproduce**

1.  drag JSON file to yt_clipper_auto_download
2.  waiting then success video generated
3.  open the video file
4.  I play the video but no audio

**Environment (Please fill the fields below):**

- Markup script version: 5.1.2
- Clipper script version: 5.1.2
- Browser: crhome 
- OS: windows

**Comment by exwm** [comment]
Hey, sorry for the late reply, I had been locked out of my account for a while.

Make sure you have audio enabled by using the extra options toggled with **Shift+W** in either the global settings or the settings for an individual marker pair.

![additional-options-menu](https://raw.githubusercontent.com/exwm/yt_clipper/master/assets/image/yt_clipper_marker_pair_editor_overrides.png)
