### ISSUE TITLE
Change the default behavior of --ytdl-location

### ISSUE THREAD

**Issue by codedealer** [exwm/yt_clipper#56]
**Please describe the need for the feature:**
Currently `--ytdl-location` is empty by default which means yt_clipper will look for yt_dlp executable in the environment's PATH variable. This makes an assumption about a user's work environment that is unnecessary since we already ship the executable along with the package.
As a result newcomers who have just installed clipper and have no yt_dlp on their system encounter an error during the first run that is confusing and hard to debug.

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/user-attachments/assets/7737d694-2ec4-401e-829a-208d75a3640d)

</p>
</details> 

**Please describe the feature and the requirements for its ideal implementation:**
Change the default for the option to point to the executable located in the `bin` folder. Advanced users can change the location at their discretion via option, but for the first run it won't have to be set by anyone that way.

**Alternative**:
Potentially we can check if the yt_dlp exists in the PATH and fallback to the local version in `bin` otherwise.

**Comment by exwm** [comment]
This was definitely the intention for frozen releases of yt_clipper. I think I missed updating the path to yt-dlp when we detect the release is frozen. Should be an easy fix.

**Comment by exwm** [comment]
Should be fixed in https://github.com/exwm/yt_clipper/releases/tag/v5.28.0
