### ISSUE TITLE
Can't resize crop

### ISSUE THREAD

**Issue by natemate2210** [exwm/yt_clipper#9]
**Describe the Bug**
Can not resize crop. It happens everytime, after I drew a crop and tried to resize it, but it won't resize. The crop moved following my mouse movements and won't stop even after I don't press the Ctrl button.

**How to Reproduce**

1.  Open any youtube video and activate the script
2. Open global settings editor (**W**)
2.  Draw a crop (**X** > **Click+Drag**)
3.  Resize drawn crop (**Ctrl+Left-Click** the border and drag it)

**Expected Behavior**
Whenever i do those steps, my mouse won't let go of the border. I even stopped pressing left click and the Ctrl button and my mouse still won't let go of the border so i can't resize my crop.

**Additional Information**
Where applicable, provide screenshots and log files generated by the python executable (AKA `clipper script`).

**Environment (Please fill the fields below):**

- Markup script version: yt_clipper_win_3.7.0-beta.4.2.0
- Clipper script version: yt_clipper_win_3.7.0-beta.4.2.0
- Browser: Chrome Version 86.0.4240.111 (Official Build) (64-bit)
- OS: Windows 10

**Additional Notes or Context**
Anything else that might help find, reproduce, and fix the bug.

**Comment by exwm** [comment]
Should be fixed in 04e0503. If you find that it is not or the fix it not satisfactory you can leave a comment and I'll reopen the issue.
